export const STRINGS ={
    call:'Call Us: 123 - 456 - 7890',
    welcome:'Welcome to Our store Multikart',
    shop:"SHOP NOW",
    trends:"BEST SELLING PRODUCTS",
    blogheader1:"Recent Story",
    blogheader2:"FROM THE BLOG",
    by:"by : ",
    comment:"Comment",
    instatag:"# INSTAGRAM",
    knowbig:"!KNOW IT ALL FIRST",
    nevemiss:"Never Miss Anything From Multikart By Signing Up To Our Newsletter",
    subscribe:"SUBSCRIBE",
    bottomitemdetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    category:"CATEGORIES",
    whywechoose:"WHY WE CHOOSE",
    storeinformation:"STORE INFORMATION",
    location:"Multikart Demo Store, Demo Store India 345-659",
    mail:"Email Us: Support@Fiot.Com",
    fax:"Fax: 123456",
    pixel:"2019 theme forest powered by pixelstrap",
    bestheader:"best selling products",
    topleft:"NEW",
    topright:"ON SALE",

}
    
