export const env = {
  apiUrl: 'http://localhost:3000/',
  assestUrl: 'http://localhost:3000/',
  // tslint:disable-next-line: max-line-length
  glbToken: '',
  accessList: [
    { _id: 'createUser', title: 'اضافه کردن کاربر' },
    { _id: 'getUsers', title: 'نمایش کاربران' },
    { _id: 'removeUser', title: 'حذف کاربران' },
    { _id: 'editUser', title: 'اصلاح کاربر' },
    { _id: 'changePass', title: ' تغییر رمز عبور کاربر' },
    { _id: 'addRoleToUser', title: 'اضافه کردن نقش به  کاربر' },
    { _id: 'removeRoleFromUser', title: 'حذف کردن نقش از  کاربر' },
    { _id: 'createRole', title: 'اضافه کردن نقش ها' },
    { _id: 'getRoles', title: 'نمایش نقش ها' },
    { _id: 'removeRole', title: 'حذف نقش ها' },
    { _id: 'editRole', title: 'اصاح نقش ها' },
    { _id: 'modifyAccessRole', title: 'اصاح دسترسی نقش ها' },
    { _id: 'getBanners', title: 'نمایش بنرها ' },
    { _id: 'createBanners', title: 'اضافه کردن بنرها' },
    { _id: 'removeBanners', title: 'حذف بنرها' },
    { _id: 'editBanners', title: 'اصلاح بنرها' },
    { _id: 'getSetting', title: 'نمایش تنظیمات' },
    { _id: 'createSetting', title: 'اضافه کردن تنظیمات' },
    { _id: 'removeSetting', title: 'حذف تنظیمات' },
    { _id: 'editSetting', title: 'اصلاح تنظیمات' },
    { _id: 'getSolution', title: 'نمایش راهکار ها' },
    { _id: 'createSolution', title: 'اضافه کردن راهکار ها' },
    { _id: 'removeSolution', title: 'حذف راهکار ها' },
    { _id: 'editSolution', title: 'اصلاح راهکار ها' },
    { _id: 'getSolutionKinds', title: 'نمایش انواع راهکار ها' },
    { _id: 'createSolutionKinds', title: 'اضافه کردن انواع راهکار ها' },
    { _id: 'removeSolutionKinds', title: 'حذف انواع راهکار ها' },
    { _id: 'editSolutionKinds', title: 'اصلاح انواع راهکار ها' },
    { _id: 'getTechnology', title: 'نمایش  تکنولوژی ها' },
    { _id: 'createTechnology', title: 'اضافه کردن  تکنولوژی ها' },
    { _id: 'removeTechnology', title: 'حذف  تکنولوژی ها' },
    { _id: 'editTechnology', title: 'اصلاح  تکنولوژی ها' },
    { _id: 'getTechnologyKinds', title: 'نمایش انواع تکنولوژی ها' },
    { _id: 'createTechnologyKinds', title: 'اضافه کردن انواع تکنولوژی ها' },
    { _id: 'removeTechnologyKinds', title: 'حذف انواع تکنولوژی ها' },
    { _id: 'editTechnologyKinds', title: 'اصلاح انواع تکنولوژی ها' },
    { _id: 'getCapability', title: 'نمایش قابلیتها' },
    { _id: 'createCapability', title: 'اضافه کردن قابلیتها' },
    { _id: 'removeCapability', title: 'حذف قابلیتها' },
    { _id: 'editCapability', title: 'اصلاح قابلیتها' },
    { _id: 'getCapabilityKind', title: 'نمایش انواع قابلیتها' },
    { _id: 'createCapabilityKind', title: 'اضافه کردن انواع قابلیتها' },
    { _id: 'removeCapabilityKind', title: 'حذف انواع قابلیتها' },
    { _id: 'editCapabilityKind', title: 'اصلاح انواع قابلیتها' },
    { _id: 'getCustomers', title: 'نمایش مشتریان' },
    { _id: 'createCustomers', title: 'اضافه کردن مشتریان' },
    { _id: 'removeCustomers', title: 'حذف مشتریان' },
    { _id: 'editCustomers', title: 'اصلاح مشتریان' },
    { _id: 'getProducts', title: 'نمایش محصولات' },
    { _id: 'createProducts', title: 'اضافه کردن محصولات' },
    { _id: 'removeProducts', title: 'حذف محصولات' },
    { _id: 'editProducts', title: 'اصلاح محصولات' },
    { _id: 'addAdvantagesToProduct', title: 'اضافه کردن مزایا به محصول' },
    { _id: 'addBannersToProduct', title: 'اضافه کردن بنر ها به محصول' },
    { _id: 'addEducationalSourcesToProduct', title: 'اضافه کردن منابع آموزشی' },
    { _id: 'addFeaturesToProduct', title: 'اضافه کردن ویژگی ها' },
    { _id: 'addTechnologyToProduct', title: 'اضافه کردن فناوری ها به محصول' },
    { _id: 'removEducationalSourcesFromProduct', title: 'حذف منبع آموزشی' },
    { _id: 'removeAdvantagesFromProduct', title: 'حذف مزایا از محصولات' },
    { _id: 'removeBannersFromProduct', title: 'حذف بنر از محصول' },
    { _id: 'removeFeaturesFromProduct', title: 'حذف ویژگی هز محصول' },
    { _id: 'removeSolutionFromProduct', title: 'حذف راهکار از محصول' },
    { _id: 'removeTechnologFromProduct', title: 'حذف فناوری از محصول' },
    { _id: 'getAdvantagesFromProduct', title: 'نمایش مزایای محصولات' },
    { _id: 'getBannersFromProduct', title: ' نمایش بنر های یک محصول' },
    { _id: 'getFeaturesFromProduct', title: 'نمایش ویژگی های محصول' },
    { _id: 'getEducationalSourcesFromProduct', title: 'نمایش منابع آموزشی محصول' },
    { _id: 'getTechnologFromProduct', title: 'نمایش فناوری های محصول' },
    { _id: 'editAdvantagesFromProduct', title: 'اصلاح مزایای محصولات' },
    { _id: 'editBannersFromProduct', title: ' اصلاح بنر های یک محصول' },
    { _id: 'editFeaturesFromProduct', title: 'اصلاح ویژگی های محصول' },
    { _id: 'editEducationalSourcesFromProduct', title: 'اصلاح منابع آموزشی محصول' },
    { _id: 'editTechnologFromProduct', title: 'اصلاح فناوری های محصول' },
    { _id: 'getFeatureDetailsFromProduct', title: ' نمایش جزییات ویژگی های محصول' },
    { _id: 'addFeatureDetailsToProduct', title: 'اضافه کردن جزییات ویژگی ها' },
    { _id: 'editFeatureDetailsFromProduct', title: 'اصلاح جزییات ویژگی های محصول' },
    { _id: 'removeFeatureDetailsFromProduct', title: 'حذف جزییات ویژگی هز محصول' },
    { _id: "getproductKinds", title: "نمایش انواع  محصولات" },
    { _id: "createproductKinds", title: "اضافه کردن انواع  محصولات" },
    { _id: "editproductKinds", title: "اصلاح انواع  محصولات" },
    { _id: "removeproductKinds", title: "حذف انواع  محصولات" },
    { _id: "getAllOrder", title: "نمایش سفارش ها" },
    { _id: "getByIdOrder", title: "نمایش سفارش بر اساس ای دی" },
    { _id: "getByStatusOrder", title: "نمایش سفارش بر اساس وضعیت" },
    { _id: "createOrder", title: "افزودن سفارش" },
    { _id: "editStatusOrder", title: "ویرایش سفارش" },
    { _id: "removeOrder", title: "حذف سفارش" },
    { _id: "getAlltransport", title: "نمایش شرکت های حمل و نقل" },
    { _id: "getByIdtransport", title: "نمایش شرکت حمل و نقل" },
    { _id: "createtransport", title: "افزودن شرکت حمل و نقل" },
    { _id: "edittransport", title: "ویرایش شرکت حمل و نقل" },
    { _id: "removetransport", title: "حذف شرکت حمل و نقل" },
    { _id: "editEducationalSourcesToProduct",title: "ویرایش منابع آموزشی محصول"},
  ]

}
